default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "caro_development") %>

test:
  <<: *default
  database: caro_test


production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "caro_production") %>
  cache:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "caro_cache_production") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "caro_queue_production") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "caro_cable_production") %>
    migrations_paths: db/cable_migrate
